services:
  db:
    container_name: postgres_db
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend/
    container_name: backend
    depends_on:
      - db
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"
volumes:
  postgres_data: