# Generated by Django 5.1.7 on 2025-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecommerceuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
